# Add your own tasks in files placed in lib/tasks ending in .rake,
# for example lib/tasks/capistrano.rake, and they will automatically be available to Rake.

require File.expand_path('../config/application', __FILE__)

Rgrids::Application.load_tasks
namespace :test do
   Rails::TestTask.new(rest: "test:prepare") do |t|
     t.pattern = 'test/rest/**/*_test.rb'
   end
   Rake::Task['test:rest'].comment = "Run tests for Grid Rest Api"
   task :run do
     Rake::Task['test:rest'].invoke
   end
   Rake::Task['test'].comment = 'test:rest'
end

#namespace :routes do
#  require File.expand_path('../lib/grid_rest_api', __FILE__)
#  puts '-' * 80
#  puts "REST Routes"
#  GridRestApi.routes["POST"].each do |r|
#    puts r[0].to_s.gsub(/\\A/,'').gsub(/\\z/, '').gsub(/\(\?\-mix\:/,'').sub(/\(\[\^\\\/\?\#\]\+\)/, ":#{r[1][0]}").sub(/\(\[\^\\\/\?\#\]\+\)/, ":#{r[1][1]}").gsub(/\\/,'').gs#ub(/\)/,'')
#  end
#  puts '-' * 80
#end
