# Add your own tasks in files placed in lib/tasks ending in .rake,
# for example lib/tasks/capistrano.rake, and they will automatically be available to Rake.

require File.expand_path('../config/application', __FILE__)

Rgrids::Application.load_tasks
namespace :test do
   Rails::TestTask.new(rest: "test:prepare") do |t|
     t.pattern = 'test/rest/**/*_test.rb'
   end
   Rake::Task['test:rest'].comment = "Run tests for Grid Rest Api"
   task :run do
     Rake::Task['test:rest'].invoke
   end
   Rake::Task['test'].comment = 'test:rest'
end
